[build]
  command = """
    curl -LsSf https://astral.sh/uv/install.sh | sh &&
    uv sync &&
    source .venv/bin/activate &&
    zensical build
  """
  publish = "site/"
  environment = { PYTHON_VERSION = "3.13" }
