[project]
name = "reservium-docs"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.14.3"
dependencies = [
    "zensical==0.0.22",
    "typer==0.23.0",
    "mkdocstrings==1.0.3",
]
