[project]
site_name = "Reservium"
repo_name = "CloudRader/reservium-api"
repo_url = "https://github.com/CloudRader/reservium-api"

nav = [
  {"User Guide" = [
    {"Introduction" = [
        "user-guide/introduction/index.md",
        "user-guide/introduction/about.md",
        "user-guide/introduction/why-use.md"
    ]},
    {"Quickstart" = [
        "user-guide/quickstart/index.md",
        "user-guide/quickstart/first-setup.md",
    ]},
    {"Basic Features" = [
        "user-guide/basic-features/index.md"
    ]},
    {"FAQ" = [
        "user-guide/faq/index.md"
    ]}
  ]},
  {"Manager Guide" = [
    {"Introduction" = [
        "manager-guide/introduction/index.md",
    ]},
  ]},
  {"Hosting Guide" = [
    {"Introduction" = [
        "hosting-guide/introduction/index.md",
    ]},
  ]},
  {"Contribute Guide" = [
    {"Introduction" = [
        "contribute-guide/introduction/index.md",
    ]},
  ]},
  {"API Reference" = [
    "api-reference/index.md",
  ]},
  {"Release Notes" = [
    "release-notes/backend.md",
    "release-notes/frontend.md",
  ]},
]

[project.theme]
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.top",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.prune",
    "navigation.indexes",
    "navigation.footer"
]

[project.theme.icon]
repo = "fontawesome/brands/github"
logo = "material/alpha-r-circle"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "default"
primary = "green"
accent = "yellow"
toggle.icon = "material/weather-night"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "slate"
primary = "green"
accent = "yellow"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to dark mode"
