[project]
site_name = "Reservium"
repo_name = "CloudRader/reservium-api"
repo_url = "https://github.com/CloudRader/reservium-api"
edit_uri = "https://github.com/CloudRader/reservium-docs/edit/main/docs/"
extra_css = ["assets/stylesheets/extra.css"]

nav = [
  {"User Guide" = [
    {"Introduction" = [
        "user-guide/introduction/index.md",
        "user-guide/introduction/about.md",
        "user-guide/introduction/why-use.md",
    ]},
    {"Quickstart" = [
        "user-guide/quickstart/index.md",
        "user-guide/quickstart/first-setup.md",
    ]},
    {"Basic Features" = [
        "user-guide/basic-features/index.md",
        "user-guide/basic-features/navigation.md",
        "user-guide/basic-features/create-reservation.md",
        "user-guide/basic-features/dashboard.md",
    ]},
    {"FAQ" = [
        "user-guide/faq/index.md"
    ]}
  ]},
  {"Manager Guide" = [
    {"Introduction" = [
        "manager-guide/introduction/index.md",
    ]},
    {"Manager Panel" = [
        "manager-guide/manager-panel/index.md",
        "manager-guide/manager-panel/manage-reservation-services.md",
        "manager-guide/manager-panel/manage-calendars.md",
        "manager-guide/manager-panel/manage-mini-services.md",
    ]},
    {"Manage Events" = [
        "manager-guide/manage-events/index.md",
    ]},
    {"FAQ" = [
        "manager-guide/faq/index.md"
    ]}
  ]},
  {"Hosting Guide" = [
    {"Introduction" = [
        "hosting-guide/introduction/index.md",
    ]},
    {"Install" = [
        "hosting-guide/install/docker.md",
    ]},
    {"Configure" = [
        "hosting-guide/configure/keycloak.md",
    ]},
    {"Update" = [
        "hosting-guide/update/docker.md",
    ]},
    {"FAQ" = [
        "hosting-guide/faq/index.md"
    ]}
  ]},
  {"Contribute Guide" = [
    {"Introduction" = [
        "contribute-guide/introduction/index.md",
    ]},
  ]},
  {"API Reference" = [
    "api-reference/index.md",
  ]},
  {"Release Notes" = [
    "release-notes/backend.md",
    "release-notes/frontend.md",
  ]},
]

[project.theme]
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.top",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.prune",
    "navigation.indexes",
    "navigation.footer",

    "content.action.edit",  # Edit this page
    "content.action.view",  # View source of this page
    "content.tooltips",
    "content.code.copy",
]
logo = "assets/logo.png"
favicon = "assets/logo.png"

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "default"
primary = "custom"
accent = "yellow"
toggle.icon = "material/weather-night"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "slate"
primary = "custom"
accent = "yellow"
toggle.icon = "material/weather-sunny"
toggle.name = "Switch to dark mode"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
